name: Update Keycloak Helm Chart

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs weekly on Monday at midnight
  workflow_dispatch:

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Install yq
        run: sudo apt-get install -y yq
    
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get the latest non-nightly tag from the Keycloak operator GitHub repository
      - name: Get Latest Non-Nightly Tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/keycloak/keycloak-k8s-resources/git/refs/tags | jq -r '.[].ref' | grep -v "nightly" | sed 's|refs/tags/||' | sort -V | tail -n 1)
          echo "Latest non-nightly tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      # Step 3: Download Keycloak manifest files to the Helm chart's templates directory
      - name: Download Keycloak CRD Manifests
        run: |
          VERSION="${{ env.tag }}"
          BASE_URL="https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/$VERSION/kubernetes"
          
          # Create the templates directory if it doesn't exist
          mkdir -p templates
          
          # Download each file into the templates folder
          curl -fL "$BASE_URL/keycloaks.k8s.keycloak.org-v1.yml" -o templates/keycloaks-crd.yml
          curl -fL "$BASE_URL/keycloakrealmimports.k8s.keycloak.org-v1.yml" -o templates/keycloakrealmimports-crd.yml
          curl -fL "$BASE_URL/kubernetes.yml" -o templates/kubernetes-operator.yml

      # Step 4: Update Chart.yaml with the latest appVersion and increment the chart version
      - name: Update Chart.yaml
        run: |
          CHART_PATH="Chart.yaml"
          VERSION="${{ env.tag }}"

          # Update the appVersion to the latest tag
          yq e ".appVersion = \"$VERSION\"" -i $CHART_PATH

          # Increment the chart version (patch version bump)
          current_version=$(yq e '.version' $CHART_PATH)
          new_version=$(echo $current_version | awk -F. '{$NF += 1; OFS="."; print $0}')
          yq e ".version = \"$new_version\"" -i $CHART_PATH

      # Step 5: Commit and push changes to the main branch
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add templates Chart.yaml
          git commit -m "Update Keycloak manifests to version $VERSION and bump chart version"
        continue-on-error: true

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Specify the branch to push to
